### PR TITLE
Add implementations for byte order conversions.

### PR DESCRIPTION
**Pull request by kortschak**
@cznic Please take a look. I had intended to include this in the previous byte order PR, but got my branches confused.

### CODE REVIEW

**Review by cznic — CHANGES_REQUESTED** [review]
I've done

```
jnml@r550:~/src/github.com/cznic/crt> git fetch origin
From github.com:cznic/crt
   6292872..3db942b  master     -> origin/master
jnml@r550:~/src/github.com/cznic/crt> git checkout -b arpa/ntohl origin/arpa/ntohl
Branch arpa/ntohl set up to track remote branch arpa/ntohl from origin.
Switched to a new branch 'arpa/ntohl'
jnml@r550:~/src/github.com/cznic/crt> git merge master
Already up-to-date.
jnml@r550:~/src/github.com/cznic/crt> 
jnml@r550:~/src/github.com/cznic/crt> make
gofmt -l -s -w *.go
GOOS=linux GOARCH=arm go build 2>&1 | tee log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
GOOS=linux GOARCH=386 go build 2>&1 | tee -a log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
GOOS=linux GOARCH=amd64 go build 2>&1 | tee -a log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
#TODO GOOS=windows GOARCH=386 go build 2>&1 | tee -a log
#TODO GOOS=windows GOARCH=amd64 go build 2>&1 | tee -a log
go test -i
go test 2>&1 | tee -a log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
FAIL	github.com/cznic/crt [build failed]
go install
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
Makefile:35: návod pro cíl „editor“ selhal
make: *** [editor] Chyba 2
jnml@r550:~/src/github.com/cznic/crt> 
```

I guess this CL depends on some other change, either one that's yet to come or one of the olders.

I'll try again after the older PRs are commited.

**Comment by kortschak** [comment]
This was undoubtedly due to my confusion. I'll fix and ping when ready.

**Comment by kortschak** [comment]
Sorry about that. PTAL

**Comment by cznic** [comment]
I'm very sorry if I'm doing something wrong, but it still fails here

```
jnml@r550:~/src/github.com/cznic/crt> git branch 
* master
  musl
jnml@r550:~/src/github.com/cznic/crt> git fetch origin
jnml@r550:~/src/github.com/cznic/crt> git checkout -b arpa/ntohl origin/arpa/ntohl
Branch arpa/ntohl set up to track remote branch arpa/ntohl from origin.
Switched to a new branch 'arpa/ntohl'
jnml@r550:~/src/github.com/cznic/crt> git merge master
Already up-to-date.
jnml@r550:~/src/github.com/cznic/crt> make
gofmt -l -s -w *.go
GOOS=linux GOARCH=arm go build 2>&1 | tee log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
GOOS=linux GOARCH=386 go build 2>&1 | tee -a log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
GOOS=linux GOARCH=amd64 go build 2>&1 | tee -a log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
#TODO GOOS=windows GOARCH=386 go build 2>&1 | tee -a log
#TODO GOOS=windows GOARCH=amd64 go build 2>&1 | tee -a log
go test -i
go test 2>&1 | tee -a log
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
FAIL	github.com/cznic/crt [build failed]
go install
# github.com/cznic/crt
./arpa_inet_linux.go:17:34: undefined: netlong
./arpa_inet_linux.go:23:20: undefined: netshort
./arpa_inet_linux.go:29:20: undefined: netshort
Makefile:35: recipe for target 'editor' failed
make: *** [editor] Error 2
jnml@r550:~/src/github.com/cznic/crt> 
```

Does running `make` succeeds at your machine?

**Review by cznic — APPROVED** [review]
LGTM, please commit to the master branch, thank you.

**Comment by kortschak** [comment]
No, that was my tiredness and dealing with ugliness of my own making. Apologies.

**Comment by kortschak** [comment]
Thanks

**Pull request merged**
