### PR TITLE
Add linux_arm

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

The issues with unused and maligned in the make run are golang/go#26257.

### CODE REVIEW

**Comment by cznic** [comment]
Thanks for the PR!

**Comment by cznic** [comment]
@kortschak My apologies, I missed that you're not yet listed in the AUTHORS and/or CONTRIBUTORS files. Please add yourself in a new PR and commit it to the master branch, thank you.

**Comment by kortschak** [comment]
Done (I don't think I have write perms).

**Comment by cznic** [comment]
I've sent you the collaborator's invitation before posting https://github.com/cznic/crt/pull/3#issuecomment-403397620. Please check your spam folder and if it's not to be found anywhere I'll resend it. Thanks.

**Pull request merged**
